### ISSUE TITLE
[Client] 이미지 파일 경로 변경

### ISSUE THREAD

**Issue by joyw93** [joyw93/pet-mate#18]
pages depth가 늘어나면 이미지 파일을 참조하지 못하는 현상이 발생하기 때문에

기존 경로 앞에 ../를 추가 해주시길 바랍니다.

</br>
</br>

기존:
src='img/sample.png'

변경 후: 
src='../img/sample.png'

**Comment by kkwakkwake** [comment]
확인 완.
